baseURL = "https://technology.amorgante.es/"
title = "Alknopfler's Site"
languageCode = "en"
enableInlineShortcodes = true
publishDir = "docs"
theme = "soho"

googleAnalytics = "G-Q2W4X5J2F1"

summarylength = 20
enableEmoji = true

[params]
author = "Alberto Morgante (a.k.a alknopfler)"
description = "My knowledge is yours"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "/images/profile.png"

copyright = "Alknopfler"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
themeColor = "#6d120e"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/albertomorgante"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/alknopfler"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About me"
  identifier = "about me"
  weight = 400
  url = "/about/"

  [[menu.main]]
  name = "Resume"
  identifier = "resume"
  weight = 500
  url = "/resume/"

    
  [[menu.main]]
  name = "Talks"
  identifier = "talks"
  weight = 300
  url = "/talks/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4
